# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
title: 'Jialing Dai'
appearance:
  mode: system
  theme_day: minimal
  theme_night: minimal
  font: classic
  color_theme: ocean

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'University of Chinese Academy of Sciences (UCAS)'
    description: 'Ph.D. candidate at UCAS and visiting researcher at UTD, focusing on data analytics, influence maximization, network diffusion, and optimization for decision making in complex systems.'
    keywords:
      - Influence Maximization
      - Network Diffusion
      - Submodular Optimization
      - Non-Submodular Optimization
      - Reinforcement Learning
      - Data-Driven Decision Analytics
      - Computational Social Networks
      - Opinion Dynamics
      - Group Behavior
      - Information Systems
      - Business Analytics
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Jialing Dai'

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Jialing Dai. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
